github:
  - Bridgetamana

# patreon: yourPatreonUsername
# open_collective: yourOpenCollective
# ko_fi: yourKofi
# buy_me_a_coffee: yourBuyMeACoffee
# liberapay: yourLiberapay
# tidelift: npm/your-package
# custom:
#   - https://your-site.com/sponsor
