name: Component Request
description: Suggest a component for Neobrutal UI
labels: ["enhancement"]
body:
  - type: textarea
    id: component-description
    attributes:
      label: Description
      description: What is the new component you are requesting?
    validations:
      required: true
