// Auto-generated by scripts/build-registry.ts — do not edit manually.
// Run `npm run registry:build` to regenerate after adding new components or docs pages.

export interface SearchItem {
    name: string
    href: string
    keywords: string[]
    category: "component" | "docs"
}

export const searchItems: SearchItem[] = [
    { name: "Accordion", href: "/docs/components/accordion", keywords: ["collapse", "and", "expand", "sections", "to", "show", "or", "hide", "content"], category: "component" },
    { name: "Alert", href: "/docs/components/alert", keywords: ["communicate", "important", "information", "or", "status", "to", "users"], category: "component" },
    { name: "Avatar", href: "/docs/components/avatar", keywords: ["display", "user", "profile", "images", "with", "automatic", "fallback", "text"], category: "component" },
    { name: "Badge", href: "/docs/components/badge", keywords: ["label", "items", "with", "status", "or", "category", "tags"], category: "component" },
    { name: "Button", href: "/docs/components/button", keywords: ["trigger", "actions", "or", "navigate", "when", "clicked"], category: "component" },
    { name: "Card", href: "/docs/components/card", keywords: ["group", "and", "organize", "related", "content", "into", "a", "contained", "unit"], category: "component" },
    { name: "Checkbox", href: "/docs/components/checkbox", keywords: ["let", "users", "select", "or", "deselect", "individual", "options"], category: "component" },
    { name: "Dialog", href: "/docs/components/dialog", keywords: ["display", "focused", "content", "in", "a", "modal", "overlay"], category: "component" },
    { name: "Input", href: "/docs/components/input", keywords: ["collect", "singleline", "text", "input", "from", "users"], category: "component" },
    { name: "Label", href: "/docs/components/label", keywords: ["associate", "descriptive", "text", "with", "form", "controls"], category: "component" },
    { name: "Pagination", href: "/docs/components/pagination", keywords: ["navigate", "through", "paginated", "content", "with", "page", "indicators"], category: "component" },
    { name: "Popover", href: "/docs/components/popover", keywords: ["show", "contextual", "content", "anchored", "to", "a", "trigger", "element"], category: "component" },
    { name: "Progress", href: "/docs/components/progress", keywords: ["visualize", "task", "completion", "progress", "with", "a", "percentage", "indicator"], category: "component" },
    { name: "Radio Group", href: "/docs/components/radio-group", keywords: ["let", "users", "select", "exactly", "one", "option", "from", "a", "group"], category: "component" },
    { name: "Select", href: "/docs/components/select", keywords: ["choose", "a", "single", "option", "from", "a", "collapsible", "list"], category: "component" },
    { name: "Slider", href: "/docs/components/slider", keywords: ["select", "a", "numeric", "value", "within", "a", "range", "using", "a", "slider"], category: "component" },
    { name: "Toast", href: "/docs/components/toast", keywords: ["show", "temporary", "notifications", "with", "automatic", "dismissal", "and", "optional", "actions"], category: "component" },
    { name: "Switch", href: "/docs/components/switch", keywords: ["toggle", "a", "boolean", "setting", "on", "or", "off"], category: "component" },
    { name: "Tabs", href: "/docs/components/tabs", keywords: ["switch", "between", "multiple", "content", "sections", "with", "tab", "controls"], category: "component" },
    { name: "Textarea", href: "/docs/components/textarea", keywords: ["collect", "multiline", "text", "input", "from", "users"], category: "component" },
    { name: "Tooltip", href: "/docs/components/tooltip", keywords: ["display", "contextual", "information", "on", "hover", "or", "focus"], category: "component" },
    { name: "Getting Started", href: "/docs", keywords: ["start", "intro", "introduction", "overview"], category: "docs" },
    { name: "Installation", href: "/docs/installation", keywords: ["setup", "install", "npm", "cli"], category: "docs" },
    { name: "Theming", href: "/docs/theming", keywords: ["theme", "colors", "customize", "tokens"], category: "docs" },
    { name: "CLI", href: "/docs/cli", keywords: ["command", "add", "terminal"], category: "docs" },
    { name: "Accessibility", href: "/docs/accessibility", keywords: ["a11y", "aria", "keyboard", "screen reader"], category: "docs" },
    { name: "Changelog", href: "/docs/changelog", keywords: ["changelog", "releases", "updates", "versions"], category: "docs" },
]
