// Auto-generated by scripts/build-registry.ts — do not edit manually.
// Run `npm run registry:build` to regenerate after adding new components or docs pages.

export interface SearchItem {
    name: string
    href: string
    keywords: string[]
    category: "component" | "docs"
}

export const searchItems: SearchItem[] = [
    { name: "Accordion", href: "/docs/components/accordion", keywords: ["a", "vertically", "stacked", "set", "of", "interactive", "headings", "that", "reveal", "content", "sections"], category: "component" },
    { name: "Alert", href: "/docs/components/alert", keywords: ["displays", "a", "callout", "for", "user", "attention", "with", "neobrutalist", "styling"], category: "component" },
    { name: "Avatar", href: "/docs/components/avatar", keywords: ["an", "image", "element", "with", "a", "fallback", "for", "representing", "the", "user"], category: "component" },
    { name: "Badge", href: "/docs/components/badge", keywords: ["displays", "a", "badge", "or", "label", "with", "neobrutalist", "styling"], category: "component" },
    { name: "Button", href: "/docs/components/button", keywords: ["displays", "a", "button", "or", "a", "component", "that", "looks", "like", "a", "button", "with", "neobrutalist", "styling"], category: "component" },
    { name: "Card", href: "/docs/components/card", keywords: ["displays", "a", "card", "with", "header", "content", "and", "footer", "sections"], category: "component" },
    { name: "Checkbox", href: "/docs/components/checkbox", keywords: ["a", "control", "that", "allows", "the", "user", "to", "toggle", "between", "checked", "and", "not", "checked"], category: "component" },
    { name: "Dialog", href: "/docs/components/dialog", keywords: ["a", "window", "overlaid", "on", "the", "primary", "window", "with", "neobrutalist", "styling"], category: "component" },
    { name: "Input", href: "/docs/components/input", keywords: ["displays", "a", "form", "input", "field", "with", "neobrutalist", "styling"], category: "component" },
    { name: "Label", href: "/docs/components/label", keywords: ["renders", "an", "accessible", "label", "associated", "with", "controls"], category: "component" },
    { name: "Pagination", href: "/docs/components/pagination", keywords: ["pagination", "with", "page", "navigation", "and", "ellipsis"], category: "component" },
    { name: "Popover", href: "/docs/components/popover", keywords: ["displays", "rich", "content", "in", "a", "portal", "triggered", "by", "a", "button"], category: "component" },
    { name: "Progress", href: "/docs/components/progress", keywords: ["displays", "an", "indicator", "showing", "the", "completion", "progress", "of", "a", "task"], category: "component" },
    { name: "Radio Group", href: "/docs/components/radio-group", keywords: ["a", "set", "of", "checkable", "buttons", "where", "only", "one", "can", "be", "checked", "at", "a", "time"], category: "component" },
    { name: "Select", href: "/docs/components/select", keywords: ["displays", "a", "list", "of", "options", "for", "the", "user", "to", "pick", "from"], category: "component" },
    { name: "Slider", href: "/docs/components/slider", keywords: ["an", "input", "where", "the", "user", "selects", "a", "value", "from", "within", "a", "given", "range"], category: "component" },
    { name: "Toast", href: "/docs/components/toast", keywords: ["an", "opinionated", "toast", "component", "with", "neobrutalist", "styling"], category: "component" },
    { name: "Switch", href: "/docs/components/switch", keywords: ["a", "control", "that", "allows", "the", "user", "to", "toggle", "between", "on", "and", "off"], category: "component" },
    { name: "Tabs", href: "/docs/components/tabs", keywords: ["a", "set", "of", "layered", "sections", "of", "content", "displayed", "one", "at", "a", "time"], category: "component" },
    { name: "Textarea", href: "/docs/components/textarea", keywords: ["displays", "a", "form", "textarea", "with", "neobrutalist", "styling"], category: "component" },
    { name: "Tooltip", href: "/docs/components/tooltip", keywords: ["a", "popup", "that", "displays", "information", "related", "to", "an", "element"], category: "component" },
    { name: "Separator", href: "/docs/components/separator", keywords: ["a", "visual", "divider", "between", "content", "sections"], category: "component" },
    { name: "Getting Started", href: "/docs", keywords: ["start", "intro", "introduction", "overview"], category: "docs" },
    { name: "Installation", href: "/docs/installation", keywords: ["setup", "install", "npm", "cli"], category: "docs" },
    { name: "Theming", href: "/docs/theming", keywords: ["theme", "colors", "customize", "tokens"], category: "docs" },
    { name: "CLI", href: "/docs/cli", keywords: ["command", "add", "terminal"], category: "docs" },
    { name: "Accessibility", href: "/docs/accessibility", keywords: ["a11y", "aria", "keyboard", "screen reader"], category: "docs" },
    { name: "Changelog", href: "/docs/changelog", keywords: ["changelog", "releases", "updates", "versions"], category: "docs" },
]
