// Auto-generated by scripts/build-registry.ts — do not edit manually.
// Run `npm run registry:build` to regenerate after adding new components or docs pages.

export interface SearchItem {
    name: string
    href: string
    keywords: string[]
    category: "component" | "docs"
}

export const searchItems: SearchItem[] = [
    { name: "Accordion", href: "/docs/components/accordion", keywords: ["collapse", "expand", "headings", "sections"], category: "component" },
    { name: "Alert", href: "/docs/components/alert", keywords: ["notification", "warning", "error", "info", "message"], category: "component" },
    { name: "Avatar", href: "/docs/components/avatar", keywords: ["user", "profile", "image", "picture", "fallback"], category: "component" },
    { name: "Badge", href: "/docs/components/badge", keywords: ["tag", "label", "status", "chip"], category: "component" },
    { name: "Button", href: "/docs/components/button", keywords: ["click", "action", "submit"], category: "component" },
    { name: "Card", href: "/docs/components/card", keywords: ["container", "panel", "surface"], category: "component" },
    { name: "Checkbox", href: "/docs/components/checkbox", keywords: ["form", "check", "tick", "input"], category: "component" },
    { name: "Dialog", href: "/docs/components/dialog", keywords: ["modal", "popup", "overlay", "window"], category: "component" },
    { name: "Input", href: "/docs/components/input", keywords: ["field", "form", "text", "type"], category: "component" },
    { name: "Label", href: "/docs/components/label", keywords: ["text", "form", "accessibility"], category: "component" },
    { name: "Pagination", href: "/docs/components/pagination", keywords: ["pages", "navigation", "next", "previous"], category: "component" },
    { name: "Popover", href: "/docs/components/popover", keywords: ["popup", "overlay", "floating", "trigger"], category: "component" },
    { name: "Progress", href: "/docs/components/progress", keywords: ["loading", "bar", "indicator", "percent"], category: "component" },
    { name: "Radio Group", href: "/docs/components/radio-group", keywords: ["form", "radio", "select", "choice"], category: "component" },
    { name: "Select", href: "/docs/components/select", keywords: ["dropdown", "form", "option", "choose"], category: "component" },
    { name: "Separator", href: "/docs/components/separator", keywords: ["divider", "line", "horizontal", "vertical"], category: "component" },
    { name: "Slider", href: "/docs/components/slider", keywords: ["range", "input", "drag", "value"], category: "component" },
    { name: "Switch", href: "/docs/components/switch", keywords: ["toggle", "on", "off", "boolean"], category: "component" },
    { name: "Tabs", href: "/docs/components/tabs", keywords: ["navigation", "panel", "content", "tab"], category: "component" },
    { name: "Textarea", href: "/docs/components/textarea", keywords: ["form", "input", "multiline", "text"], category: "component" },
    { name: "Toast", href: "/docs/components/toast", keywords: ["notification", "alert", "sonner", "message", "toaster"], category: "component" },
    { name: "Tooltip", href: "/docs/components/tooltip", keywords: ["hint", "help", "hover", "info"], category: "component" },
    { name: "Getting Started", href: "/docs", keywords: ["start", "intro", "introduction", "overview"], category: "docs" },
    { name: "Installation", href: "/docs/installation", keywords: ["setup", "install", "npm", "cli"], category: "docs" },
    { name: "Theming", href: "/docs/theming", keywords: ["theme", "colors", "customize", "tokens"], category: "docs" },
    { name: "CLI", href: "/docs/cli", keywords: ["command", "add", "terminal"], category: "docs" },
    { name: "Accessibility", href: "/docs/accessibility", keywords: ["a11y", "aria", "keyboard", "screen reader"], category: "docs" },
    { name: "Changelog", href: "/docs/changelog", keywords: ["changelog", "releases", "updates", "versions"], category: "docs" },
]
