import * as fs from "fs/promises"
import * as path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT_DIR = path.resolve(__dirname, "..")
const OUTPUT_DIR = path.resolve(ROOT_DIR, "public/r")

interface RegistryFile {
    path: string
    type: string
}

interface RegistryItem {
    name: string
    type: string
    description?: string
    dependencies?: string[]
    devDependencies?: string[]
    registryDependencies?: string[]
    files: RegistryFile[]
}

interface Registry {
    name: string
    homepage: string
    items: RegistryItem[]
}

async function buildRegistry() {
    console.log("Building registry...")

    const registryPath = path.resolve(ROOT_DIR, "registry.json")
    const registryContent = await fs.readFile(registryPath, "utf-8")
    const registry: Registry = JSON.parse(registryContent)

    await fs.mkdir(OUTPUT_DIR, { recursive: true })

    const index: Array<{
        name: string
        type: string
        description?: string
        dependencies?: string[]
        registryDependencies?: string[]
    }> = []

    for (const item of registry.items) {
        console.log(`  Building ${item.name}...`)

        const filesWithContent = await Promise.all(
            item.files.map(async (file) => {
                const filePath = path.resolve(ROOT_DIR, file.path)
                const content = await fs.readFile(filePath, "utf-8")
                return {
                    path: file.path,
                    content,
                    type: file.type,
                }
            })
        )

        const outputItem = {
            $schema: "https://ui.shadcn.com/schema/registry-item.json",
            name: item.name,
            type: item.type,
            description: item.description,
            dependencies: item.dependencies,
            devDependencies: item.devDependencies,
            registryDependencies: item.registryDependencies,
            files: filesWithContent,
        }

        const outputPath = path.resolve(OUTPUT_DIR, `${item.name}.json`)
        await fs.writeFile(outputPath, JSON.stringify(outputItem, null, 2), "utf-8")

        index.push({
            name: item.name,
            type: item.type,
            description: item.description,
            dependencies: item.dependencies,
            registryDependencies: item.registryDependencies,
        })
    }

    const indexPath = path.resolve(OUTPUT_DIR, "index.json")
    await fs.writeFile(indexPath, JSON.stringify(index, null, 2), "utf-8")

    console.log(`\nBuilt ${registry.items.length} registry items to ${OUTPUT_DIR}`)

    // Generate lib/search-data.ts from registry + static docs pages
    const componentItems = registry.items
        .filter((item) => item.type === "registry:ui")
        .map((item) => {
            const name = item.name
                .split("-")
                .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
                .join(" ")
            const keywords = (item.description ?? "")
                .toLowerCase()
                .replace(/[^a-z0-9 ]/g, "")
                .split(" ")
                .filter(Boolean)
            return `    { name: "${name}", href: "/docs/components/${item.name}", keywords: [${keywords.map((k) => `"${k}"`).join(", ")}], category: "component" },`
        })
        .join("\n")

    const docsItems = [
        `    { name: "Getting Started", href: "/docs", keywords: ["start", "intro", "introduction", "overview"], category: "docs" },`,
        `    { name: "Installation", href: "/docs/installation", keywords: ["setup", "install", "npm", "cli"], category: "docs" },`,
        `    { name: "Theming", href: "/docs/theming", keywords: ["theme", "colors", "customize", "tokens"], category: "docs" },`,
        `    { name: "CLI", href: "/docs/cli", keywords: ["command", "add", "terminal"], category: "docs" },`,
        `    { name: "Accessibility", href: "/docs/accessibility", keywords: ["a11y", "aria", "keyboard", "screen reader"], category: "docs" },`,
        `    { name: "Changelog", href: "/docs/changelog", keywords: ["changelog", "releases", "updates", "versions"], category: "docs" },`,
    ].join("\n")

    const searchDataContent = `// Auto-generated by scripts/build-registry.ts — do not edit manually.
// Run \`npm run registry:build\` to regenerate after adding new components or docs pages.

export interface SearchItem {
    name: string
    href: string
    keywords: string[]
    category: "component" | "docs"
}

export const searchItems: SearchItem[] = [
${componentItems}
${docsItems}
]
`
    const searchDataPath = path.resolve(ROOT_DIR, "lib/search-data.ts")
    await fs.writeFile(searchDataPath, searchDataContent, "utf-8")
    console.log("Generated lib/search-data.ts")

    console.log("Done!")
}

buildRegistry().catch(console.error)
